version: '3.8'

services:
  tesseract:
    image: gscloudcz/tesseract-lasagna:latest
    container_name: tesseract-lasagna
    ports:
      - "9000:80"
    volumes:
      # customization = templates, routers, config, presenters
      - ./custom:/var/www/custom
      # persistence
      - ./data:/var/www/data
      - ./logs:/var/www/logs
      # static assets
      - ./www/download:/var/www/www/download
      - ./www/upload:/var/www/www/upload
      - ./www/img/logo.png:/var/www/www/img/logo.png
    environment:
      - TZ=Europe/Prague
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/en"]
      interval: 10s
      timeout: 5s
      retries: 3
